# heroku pg:backups public-url -a poetic-checkins
# pg_restore --verbose --clean --no-acl --no-owner -h localhost -d butler-checkin_development ~/DOWNLOADS/a.dump
# heroku pg:backups restore 'backup_url' HEROKU_POSTGRESQL_BROWN_URL -a faith-in-practice-staging

development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: butler-checkin_development
  pool:     5
  # username: butler-checkin
  # password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: butler-checkin_test
  pool:     5
  username: butler-checkin
  password:
  template: template0

production:
  database: butler-checkin_production
