# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: a98f0bde928820c07311a5ac8e80379af591ce93435f30e410a656789307edf3f56db816fb3f97ec704b9b18343bd08089b01bf82ac5ca6a3560d36b0164b933

test:
  domain_name: example.com 
  secret_key_base: b43f7c59f4a35177d784cec5f2652388e08faed1240ef532771302a7fd412135ced2028ce51f6caaaa086bf4125a8042a5e143e4820faedcdf241f8230838ccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
